a = 10
b= 15
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division (float):", a / b)
print("Floor Division (integer result):", a // b)
print("Modulus (Remainder):", a % b)
print("Exponentiation:", a ** b)
print("Complex Number:", complex(a, b))
print("Absolute Value of -a:", abs(-a))
print("Power (a^b):", pow(a, b))
print("Square Root of a:", a ** 0.5)
print("Square Root of b:", b ** 0.5)
print("Max of a and b:", max(a, b))
print("Min of a and b:", min(a, b))
print("Round a:", round(a))
print("Round b:", round(b))
print("Type of a:", type(a))
print("Type of b:", type(b))
print("Type of complex number:", type(complex(a, b)))
print("Type of absolute value:", type(abs(-a)))
print("Type of power result:", type(pow(a, b)))
print("Type of square root of a:", type(a ** 0.5))
print("Type of square root of b:", type(b ** 0.5))
print("Type of max value:", type(max(a, b)))
print("Type of min value:", type(min(a, b)))
print("Type of rounded a:", type(round(a)))
print("Type of rounded b:", type(round(b)))
print("Is a greater than b?", a > b)
print("Is a less than b?", a < b)
print("Is a equal to b?", a == b)
print("Is a not equal to b?", a != b)
print("Is a greater than or equal to b?", a >= b)
print("Is a less than or equal to b?", a <= b)
print("Logical AND (a > 5 and b < 20):", a > 5 and b < 20)
print("Logical OR (a < 5 or b < 20):", a < 5 or b < 20)
print("Logical NOT (not (a > b)):", not (a > b))
print("Type of comparison (a > b):", type(a > b))
print("Type of logical AND:", type(a > 5 and b < 20))
print("Type of logical OR:", type(a < 5 or b < 20))
print("Type of logical NOT:", type(not (a > b)))
print("End of arithmetic operations demo.")
# This is a simple Python script demonstrating various arithmetic operations and their types.